name = "SecureArithmetic"
uuid = "38cee09b-6d7e-4d21-866e-807a7f642fe9"
authors = ["Michael Schlottke-Lakemper <michael@sloede.com>"]
version = "0.2.1-dev"

[deps]
OpenFHE = "77ce9b8e-ecf5-45d1-bd8a-d31f384f2f95"

[compat]
OpenFHE = "0.1.12"
julia = "1.11"
